[colors.primary]
background = '#13140d'
foreground = '#e5e3d6'
 
[colors.cursor]
text = '#e5e3d6'
cursor = '#c8c7b7' 
 
[colors.vi_mode_cursor]
text = '#13140d'
cursor = '#c4cd7b' 
 
[colors.search.matches]
foreground = '#47483b' 
background = '#a2d0c1' 
 
[colors.search.focused_match]
foreground = '#47483b' 
background = '#c4cd7b' 
 
[colors.footer_bar]
foreground = '#47483b' 
background = '#e5e3d6' 
 
[colors.hints.start]
foreground = '#47483b' 
background = '#c7c9a7' 
 
[colors.hints.end]
foreground = '#47483b' 
background = '#c7c9a7' 
 
[colors.selection]
text = '#13140d'
background = '#c4cd7b'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#c4cd7b' 
yellow = '#5b631e' 
blue = '#c4cd7b' 
magenta = '#a2d0c1' 
cyan = '#c7c9a7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
